# Generated by Django 2.1.4 on 2019-01-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop1',
            name='eid',
            field=models.CharField(auto_created=True, max_length=10),
        ),
    ]
